## Jumia Data Cleaning

In [1]:
#importing library for data cleaning

import pandas as pd
import numpy as np
import re

In [2]:
# importing dataset for data cleaning

df = pd.read_csv(r"C:\Users\ikeol\OneDrive\Documents\Web-Scraping\Data\Jumia Phones data.csv")
df

,Unnamed: 0,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,"₦ 128,468","₦ 131,172",4 out of 5,(2010 verified ratings)
1,1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,"₦ 109,706","₦ 111,330",4 out of 5,(919 verified ratings)
2,2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,"₦ 179,823","₦ 188,814",4.2 out of 5,(1036 verified ratings)
3,3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,"₦ 6,846","₦ 7,188",3.7 out of 5,(3175 verified ratings)
4,4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,"₦ 142,879","₦ 150,023",4.1 out of 5,(396 verified ratings)
...,...,...,...,...,...,...,...,...
355,355,2026-02-23,"Samsung Galaxy S20 5G - 6.2"" 128GB/12GB, Singl...",Samsung,"₦ 260,000","₦ 300,000",4.1 out of 5,(7 verified ratings)
356,356,2026-02-23,"Doogee Local Stock Note58 6.75"" iPhone-Style 5...",Doogee,"₦ 184,439","₦ 430,610",0 out of 5,NaN
357,357,2026-02-23,"Samsung Galaxy A17 5G 6.7"" 8GB RAM 256GB ROM ...",Samsung,"₦ 335,000",NaN,4 out of 5,(1 verified rating)
358,358,2026-02-23,"Samsung Galaxy S22 Ultra 5G- 6.8"" - 256GB ROM,...",Samsung,"₦ 610,000",NaN,5 out of 5,(2 verified ratings)
359,359,2026-02-23,"Samsung Galaxy A56 5G 6.7"" 8GB RAM 256GB ROM ...",Samsung,"₦ 540,000",NaN,4.8 out of 5,(9 verified ratings)

In [3]:
df.dtypes

Unnamed: 0     int64
Today         object
Title         object
Brand         object
Price         object
Old Price     object
Rating        object
Reviews       object
dtype: object

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  360 non-null    int64
 1   Today       360 non-null    object
 2   Title       360 non-null    object
 3   Brand       360 non-null    object
 4   Price       360 non-null    object
 5   Old Price   286 non-null    object
 6   Rating      360 non-null    object
 7   Reviews     316 non-null    object
dtypes: int64(1), object(7)
memory usage: 22.6+ KB

In [5]:
#Removed duplicate values from the dataframe

df = df.drop_duplicates()
df

,Unnamed: 0,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,"₦ 128,468","₦ 131,172",4 out of 5,(2010 verified ratings)
1,1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,"₦ 109,706","₦ 111,330",4 out of 5,(919 verified ratings)
2,2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,"₦ 179,823","₦ 188,814",4.2 out of 5,(1036 verified ratings)
3,3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,"₦ 6,846","₦ 7,188",3.7 out of 5,(3175 verified ratings)
4,4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,"₦ 142,879","₦ 150,023",4.1 out of 5,(396 verified ratings)
...,...,...,...,...,...,...,...,...
355,355,2026-02-23,"Samsung Galaxy S20 5G - 6.2"" 128GB/12GB, Singl...",Samsung,"₦ 260,000","₦ 300,000",4.1 out of 5,(7 verified ratings)
356,356,2026-02-23,"Doogee Local Stock Note58 6.75"" iPhone-Style 5...",Doogee,"₦ 184,439","₦ 430,610",0 out of 5,NaN
357,357,2026-02-23,"Samsung Galaxy A17 5G 6.7"" 8GB RAM 256GB ROM ...",Samsung,"₦ 335,000",NaN,4 out of 5,(1 verified rating)
358,358,2026-02-23,"Samsung Galaxy S22 Ultra 5G- 6.8"" - 256GB ROM,...",Samsung,"₦ 610,000",NaN,5 out of 5,(2 verified ratings)
359,359,2026-02-23,"Samsung Galaxy A56 5G 6.7"" 8GB RAM 256GB ROM ...",Samsung,"₦ 540,000",NaN,4.8 out of 5,(9 verified ratings)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  360 non-null    int64
 1   Today       360 non-null    object
 2   Title       360 non-null    object
 3   Brand       360 non-null    object
 4   Price       360 non-null    object
 5   Old Price   286 non-null    object
 6   Rating      360 non-null    object
 7   Reviews     316 non-null    object
dtypes: int64(1), object(7)
memory usage: 22.6+ KB

In [7]:
#Dropped the column "Not_Useful_column" cause of its irrelevance to the dataset

df = df.drop(columns = "Unnamed: 0")
df

,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,"₦ 128,468","₦ 131,172",4 out of 5,(2010 verified ratings)
1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,"₦ 109,706","₦ 111,330",4 out of 5,(919 verified ratings)
2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,"₦ 179,823","₦ 188,814",4.2 out of 5,(1036 verified ratings)
3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,"₦ 6,846","₦ 7,188",3.7 out of 5,(3175 verified ratings)
4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,"₦ 142,879","₦ 150,023",4.1 out of 5,(396 verified ratings)
...,...,...,...,...,...,...,...
355,2026-02-23,"Samsung Galaxy S20 5G - 6.2"" 128GB/12GB, Singl...",Samsung,"₦ 260,000","₦ 300,000",4.1 out of 5,(7 verified ratings)
356,2026-02-23,"Doogee Local Stock Note58 6.75"" iPhone-Style 5...",Doogee,"₦ 184,439","₦ 430,610",0 out of 5,NaN
357,2026-02-23,"Samsung Galaxy A17 5G 6.7"" 8GB RAM 256GB ROM ...",Samsung,"₦ 335,000",NaN,4 out of 5,(1 verified rating)
358,2026-02-23,"Samsung Galaxy S22 Ultra 5G- 6.8"" - 256GB ROM,...",Samsung,"₦ 610,000",NaN,5 out of 5,(2 verified ratings)
359,2026-02-23,"Samsung Galaxy A56 5G 6.7"" 8GB RAM 256GB ROM ...",Samsung,"₦ 540,000",NaN,4.8 out of 5,(9 verified ratings)

In [8]:
df.head(50)

,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,"₦ 128,468","₦ 131,172",4 out of 5,(2010 verified ratings)
1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,"₦ 109,706","₦ 111,330",4 out of 5,(919 verified ratings)
2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,"₦ 179,823","₦ 188,814",4.2 out of 5,(1036 verified ratings)
3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,"₦ 6,846","₦ 7,188",3.7 out of 5,(3175 verified ratings)
4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,"₦ 142,879","₦ 150,023",4.1 out of 5,(396 verified ratings)
5,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,"₦ 90,100","₦ 105,000",4 out of 5,(146 verified ratings)
6,2026-02-23,"itel 2165 Wireless FM, Torch, Dual SIM Phone +...",itel,"₦ 9,990","₦ 18,000",3.7 out of 5,(2886 verified ratings)
7,2026-02-23,XIAOMI Redmi 15C 6.9'' 6GBRAM/128GB ROM Androi...,XIAOMI,"₦ 153,206","₦ 160,866",4.4 out of 5,(147 verified ratings)
8,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,"₦ 108,200","₦ 118,280",4.3 out of 5,(103 verified ratings)
9,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/64GB ROM Andro...",Samsung,"₦ 118,607","₦ 127,518",4.1 out of 5,(1076 verified ratings)
10,2026-02-23,"Sunelan S7 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,"₦ 6,846","₦ 7,188",3.7 out of 5,(2994 verified ratings)
11,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,"₦ 90,100","₦ 105,000",4 out of 5,(73 verified ratings)
12,2026-02-23,"Philips Fun100 Wireless FM,2.0'' Big Screen,4M...",Philips,"₦ 9,400","₦ 12,300",4 out of 5,(713 verified ratings)
13,2026-02-23,"C Idea C10 6.79 inch phone, 3GB Ram 64GB Rom s...",C Idea,"₦ 81,950","₦ 111,750",3.3 out of 5,(126 verified ratings)
14,2026-02-23,"itel City 100 7.65mm"" Slim Design 5200mah And...",itel,"₦ 123,000","₦ 135,910",4.1 out of 5,(364 verified ratings)
15,2026-02-23,"C Idea C11 6.79 inch phone,3GB Ram 64GB Rom st...",C Idea,"₦ 81,000","₦ 89,400",3.2 out of 5,(166 verified ratings)
16,2026-02-23,"itel City 100 7.65mm"" Slim Design 5200mah And...",itel,"₦ 123,000","₦ 135,910",4.1 out of 5,(215 verified ratings)
17,2026-02-23,"Sunelan S7 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,"₦ 6,846","₦ 7,188",3.8 out of 5,(913 verified ratings)
18,2026-02-23,redbeat D5 Smartphone 6.52inch IPS HD 4GB + 64...,redbeat,"₦ 84,930","₦ 132,610",3.8 out of 5,(188 verified ratings)
19,2026-02-23,"XIAOMI Redmi A3 Pro 6.88"" 4GB RAM / 128GB ROM ...",XIAOMI,"₦ 124,926","₦ 131,172",3.9 out of 5,(413 verified ratings)
20,2026-02-23,"Poco C71 6.88"" 4GB RAM / 128GB ROM Android 15...",Poco,"₦ 119,721","₦ 125,707",4.1 out of 5,(178 verified ratings)
21,2026-02-23,"XIAOMI Redmi A3 Pro 6.88"" 4GB RAM / 128GB ROM ...",XIAOMI,"₦ 124,926","₦ 131,172",4 out of 5,(361 verified ratings)
22,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,"₦ 6,846","₦ 7,188",3.8 out of 5,(972 verified ratings)
23,2026-02-23,"Poco C71 6.88"" 3GB RAM / 64GB ROM Android 15 ...",Poco,"₦ 102,182","₦ 107,291",4.1 out of 5,(157 verified ratings)
24,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,"₦ 108,200","₦ 118,280",4.3 out of 5,(73 verified ratings)
25,2026-02-23,"Poco C71 6.88"" 3GB RAM / 64GB ROM Android 15 -...",Poco,"₦ 99,999","₦ 107,291",4.1 out of 5,(43 verified ratings)
26,2026-02-23,"FreeYond FreeYond M5,4GB+128GB,4G 6.52"" Smartp...",FreeYond,"₦ 90,499","₦ 195,205",3.8 out of 5,(288 verified ratings)
27,2026-02-23,"Nokia 105_African Edition 1.77"" 4MB/4MB 800 MA...",Nokia,"₦ 13,150","₦ 24,000",3.9 out of 5,(818 verified ratings)
28,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/ 128GB ROM And...",Samsung,"₦ 140,327","₦ 152,100",4.2 out of 5,(563 verified ratings)
29,2026-02-23,CALLONG CA 800 Wireless FM Torchlight Dual SIM...,CALLONG,"₦ 8,200","₦ 17,438",3.8 out of 5,(173 verified ratings)
30,2026-02-23,Samsung Galaxy A06 4GB RAM + 128GB ROM BLACK,Samsung,"₦ 142,990","₦ 180,000",4.1 out of 5,(119 verified ratings)
31,2026-02-23,"AGM Note N1 6.52"" 8GB Base RAM/8GB Extended RA...",AGM,"₦ 95,860","₦ 153,063",3.9 out of 5,(512 verified ratings)
32,2026-02-23,"Tecno T101 1.8"" Dual SIM - Black",Tecno,"₦ 13,263","₦ 13,926",3.8 out of 5,(1362 verified ratings)
33,2026-02-23,"FreeYond FreeYond M5,8GB+128GB,4G 6.52"" Smartp...",FreeYond,"₦ 93,299","₦ 196,188",4 out of 5,(256 verified ratings)
34,2026-02-23,XIAOMI Redmi 15 6.9'' 6GBRAM/128GB ROM Android...,XIAOMI,"₦ 194,368","₦ 204,086",4.6 out of 5,(73 verified ratings)
35,2026-02-23,Philips Essence 20 6.56 HD Punch Hole 128GB RO...,Philips,"₦ 112,000","₦ 139,020",4.1 out of 5,(76 verified ratings)
36,2026-02-23,"Samsung Galaxy A07 6.7"" 4GB RAM/ 128GB ROM And...",Samsung,"₦ 160,990","₦ 180,000",4.2 out of 5,(108 verified ratings)
37,2026-02-23,"Oukitel C61, 6.88"" HD+, 5150mAh, 16GB RAM + 12...",Oukitel,"₦ 159,920 - ₦ 160,920","₦ 207,229",3.3 out of 5,(72 verified ratings)
38,2026-02-23,Dual SIM Dual Standby Foldable Mini Flip 2G Mo...,(134 verified ratings),"₦ 23,959","₦ 51,703",4.1 out of 5,(134 verified ratings)
39,2026-02-23,Oppo A3S- 4G LTE Dual SIM 6.2'' 4GB RAM+64GB R...,(16 verified ratings),"₦ 66,090","₦ 149,000",4.3 out of 5,(16 verified ratings)
40,2026-02-23,Philips Essence 20 6.56 HD Punch Hole 128GB RO...,Philips,"₦ 112,000","₦ 139,000",4 out of 5,(31 verified ratings)
41,2026-02-23,Samsung Galaxy A06 4GB RAM + 64GB ROM BLACK,Samsung,"₦ 120,990","₦ 165,000",3.9 out of 5,(63 verified ratings)
42,2026-02-23,Philips Fun100 Wireless FM - Deep Blue,Philips,"₦ 9,500","₦ 12,300",4.1 out of 5,(352 verified ratings)
43,2026-02-23,Samsung Galaxy Note20 SINGLE SIM (128GB 8GB RA...,Samsung,"₦ 298,000","₦ 433,794",3.9 out of 5,(28 verified ratings)
44,2026-02-23,"Poco C85 6.9"" 6GB RAM / 128GB ROM Xiaomi Hyper...",Poco,"₦ 150,295","₦ 157,810",4.4 out of 5,(63 verified ratings)
45,2026-02-23,Philips Fun100 Wireless FM - Black,Philips,"₦ 9,500","₦ 12,300",4.1 out of 5,(278 verified ratings)
46,2026-02-23,Samsung Galaxy A06 4GB RAM + 128GB ROM LIGHT BLUE,Samsung,"₦ 142,990","₦ 180,000",4 out of 5,(73 verified ratings)
47,2026-02-23,itel it5095P Music 500 dual sim 2.8inc QQVA Su...,itel,"₦ 22,200","₦ 28,990",4.5 out of 5,(20 verified ratings)
48,2026-02-23,"Samsung Galaxy A07 6.7"" 4GB RAM/64GBGB ROM - B...",Samsung,"₦ 136,693","₦ 147,707",4.5 out of 5,(29 verified ratings)
49,2026-02-23,Oppo A3S 4GB RAM+ 64GB ROM-4G LTE Dual SIM -6....,(49 verified ratings),"₦ 67,050","₦ 93,125",3.4 out of 5,(49 verified ratings)

In [9]:
df["Price"] = df["Price"].str.strip("₦")
df["Old Price"] = df["Old Price"].str.strip("₦")

df.head(30)

,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,"128,468","131,172",4 out of 5,(2010 verified ratings)
1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,"109,706","111,330",4 out of 5,(919 verified ratings)
2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,"179,823","188,814",4.2 out of 5,(1036 verified ratings)
3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,"6,846","7,188",3.7 out of 5,(3175 verified ratings)
4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,"142,879","150,023",4.1 out of 5,(396 verified ratings)
5,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,"90,100","105,000",4 out of 5,(146 verified ratings)
6,2026-02-23,"itel 2165 Wireless FM, Torch, Dual SIM Phone +...",itel,"9,990","18,000",3.7 out of 5,(2886 verified ratings)
7,2026-02-23,XIAOMI Redmi 15C 6.9'' 6GBRAM/128GB ROM Androi...,XIAOMI,"153,206","160,866",4.4 out of 5,(147 verified ratings)
8,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,"108,200","118,280",4.3 out of 5,(103 verified ratings)
9,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/64GB ROM Andro...",Samsung,"118,607","127,518",4.1 out of 5,(1076 verified ratings)
10,2026-02-23,"Sunelan S7 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,"6,846","7,188",3.7 out of 5,(2994 verified ratings)
11,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,"90,100","105,000",4 out of 5,(73 verified ratings)
12,2026-02-23,"Philips Fun100 Wireless FM,2.0'' Big Screen,4M...",Philips,"9,400","12,300",4 out of 5,(713 verified ratings)
13,2026-02-23,"C Idea C10 6.79 inch phone, 3GB Ram 64GB Rom s...",C Idea,"81,950","111,750",3.3 out of 5,(126 verified ratings)
14,2026-02-23,"itel City 100 7.65mm"" Slim Design 5200mah And...",itel,"123,000","135,910",4.1 out of 5,(364 verified ratings)
15,2026-02-23,"C Idea C11 6.79 inch phone,3GB Ram 64GB Rom st...",C Idea,"81,000","89,400",3.2 out of 5,(166 verified ratings)
16,2026-02-23,"itel City 100 7.65mm"" Slim Design 5200mah And...",itel,"123,000","135,910",4.1 out of 5,(215 verified ratings)
17,2026-02-23,"Sunelan S7 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,"6,846","7,188",3.8 out of 5,(913 verified ratings)
18,2026-02-23,redbeat D5 Smartphone 6.52inch IPS HD 4GB + 64...,redbeat,"84,930","132,610",3.8 out of 5,(188 verified ratings)
19,2026-02-23,"XIAOMI Redmi A3 Pro 6.88"" 4GB RAM / 128GB ROM ...",XIAOMI,"124,926","131,172",3.9 out of 5,(413 verified ratings)
20,2026-02-23,"Poco C71 6.88"" 4GB RAM / 128GB ROM Android 15...",Poco,"119,721","125,707",4.1 out of 5,(178 verified ratings)
21,2026-02-23,"XIAOMI Redmi A3 Pro 6.88"" 4GB RAM / 128GB ROM ...",XIAOMI,"124,926","131,172",4 out of 5,(361 verified ratings)
22,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,"6,846","7,188",3.8 out of 5,(972 verified ratings)
23,2026-02-23,"Poco C71 6.88"" 3GB RAM / 64GB ROM Android 15 ...",Poco,"102,182","107,291",4.1 out of 5,(157 verified ratings)
24,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,"108,200","118,280",4.3 out of 5,(73 verified ratings)
25,2026-02-23,"Poco C71 6.88"" 3GB RAM / 64GB ROM Android 15 -...",Poco,"99,999","107,291",4.1 out of 5,(43 verified ratings)
26,2026-02-23,"FreeYond FreeYond M5,4GB+128GB,4G 6.52"" Smartp...",FreeYond,"90,499","195,205",3.8 out of 5,(288 verified ratings)
27,2026-02-23,"Nokia 105_African Edition 1.77"" 4MB/4MB 800 MA...",Nokia,"13,150","24,000",3.9 out of 5,(818 verified ratings)
28,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/ 128GB ROM And...",Samsung,"140,327","152,100",4.2 out of 5,(563 verified ratings)
29,2026-02-23,CALLONG CA 800 Wireless FM Torchlight Dual SIM...,CALLONG,"8,200","17,438",3.8 out of 5,(173 verified ratings)

In [10]:
# making the prices (current and old) in numbers

df["Price"] = df["Price"].str.replace("," , "")
df["Old Price"] = df["Old Price"].str.replace("," , "")

df.head(50)

,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,128468,131172,4 out of 5,(2010 verified ratings)
1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,109706,111330,4 out of 5,(919 verified ratings)
2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,179823,188814,4.2 out of 5,(1036 verified ratings)
3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.7 out of 5,(3175 verified ratings)
4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,142879,150023,4.1 out of 5,(396 verified ratings)
5,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,90100,105000,4 out of 5,(146 verified ratings)
6,2026-02-23,"itel 2165 Wireless FM, Torch, Dual SIM Phone +...",itel,9990,18000,3.7 out of 5,(2886 verified ratings)
7,2026-02-23,XIAOMI Redmi 15C 6.9'' 6GBRAM/128GB ROM Androi...,XIAOMI,153206,160866,4.4 out of 5,(147 verified ratings)
8,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,108200,118280,4.3 out of 5,(103 verified ratings)
9,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/64GB ROM Andro...",Samsung,118607,127518,4.1 out of 5,(1076 verified ratings)
10,2026-02-23,"Sunelan S7 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.7 out of 5,(2994 verified ratings)
11,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,90100,105000,4 out of 5,(73 verified ratings)
12,2026-02-23,"Philips Fun100 Wireless FM,2.0'' Big Screen,4M...",Philips,9400,12300,4 out of 5,(713 verified ratings)
13,2026-02-23,"C Idea C10 6.79 inch phone, 3GB Ram 64GB Rom s...",C Idea,81950,111750,3.3 out of 5,(126 verified ratings)
14,2026-02-23,"itel City 100 7.65mm"" Slim Design 5200mah And...",itel,123000,135910,4.1 out of 5,(364 verified ratings)
15,2026-02-23,"C Idea C11 6.79 inch phone,3GB Ram 64GB Rom st...",C Idea,81000,89400,3.2 out of 5,(166 verified ratings)
16,2026-02-23,"itel City 100 7.65mm"" Slim Design 5200mah And...",itel,123000,135910,4.1 out of 5,(215 verified ratings)
17,2026-02-23,"Sunelan S7 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.8 out of 5,(913 verified ratings)
18,2026-02-23,redbeat D5 Smartphone 6.52inch IPS HD 4GB + 64...,redbeat,84930,132610,3.8 out of 5,(188 verified ratings)
19,2026-02-23,"XIAOMI Redmi A3 Pro 6.88"" 4GB RAM / 128GB ROM ...",XIAOMI,124926,131172,3.9 out of 5,(413 verified ratings)
20,2026-02-23,"Poco C71 6.88"" 4GB RAM / 128GB ROM Android 15...",Poco,119721,125707,4.1 out of 5,(178 verified ratings)
21,2026-02-23,"XIAOMI Redmi A3 Pro 6.88"" 4GB RAM / 128GB ROM ...",XIAOMI,124926,131172,4 out of 5,(361 verified ratings)
22,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.8 out of 5,(972 verified ratings)
23,2026-02-23,"Poco C71 6.88"" 3GB RAM / 64GB ROM Android 15 ...",Poco,102182,107291,4.1 out of 5,(157 verified ratings)
24,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,108200,118280,4.3 out of 5,(73 verified ratings)
25,2026-02-23,"Poco C71 6.88"" 3GB RAM / 64GB ROM Android 15 -...",Poco,99999,107291,4.1 out of 5,(43 verified ratings)
26,2026-02-23,"FreeYond FreeYond M5,4GB+128GB,4G 6.52"" Smartp...",FreeYond,90499,195205,3.8 out of 5,(288 verified ratings)
27,2026-02-23,"Nokia 105_African Edition 1.77"" 4MB/4MB 800 MA...",Nokia,13150,24000,3.9 out of 5,(818 verified ratings)
28,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/ 128GB ROM And...",Samsung,140327,152100,4.2 out of 5,(563 verified ratings)
29,2026-02-23,CALLONG CA 800 Wireless FM Torchlight Dual SIM...,CALLONG,8200,17438,3.8 out of 5,(173 verified ratings)
30,2026-02-23,Samsung Galaxy A06 4GB RAM + 128GB ROM BLACK,Samsung,142990,180000,4.1 out of 5,(119 verified ratings)
31,2026-02-23,"AGM Note N1 6.52"" 8GB Base RAM/8GB Extended RA...",AGM,95860,153063,3.9 out of 5,(512 verified ratings)
32,2026-02-23,"Tecno T101 1.8"" Dual SIM - Black",Tecno,13263,13926,3.8 out of 5,(1362 verified ratings)
33,2026-02-23,"FreeYond FreeYond M5,8GB+128GB,4G 6.52"" Smartp...",FreeYond,93299,196188,4 out of 5,(256 verified ratings)
34,2026-02-23,XIAOMI Redmi 15 6.9'' 6GBRAM/128GB ROM Android...,XIAOMI,194368,204086,4.6 out of 5,(73 verified ratings)
35,2026-02-23,Philips Essence 20 6.56 HD Punch Hole 128GB RO...,Philips,112000,139020,4.1 out of 5,(76 verified ratings)
36,2026-02-23,"Samsung Galaxy A07 6.7"" 4GB RAM/ 128GB ROM And...",Samsung,160990,180000,4.2 out of 5,(108 verified ratings)
37,2026-02-23,"Oukitel C61, 6.88"" HD+, 5150mAh, 16GB RAM + 12...",Oukitel,159920 - ₦ 160920,207229,3.3 out of 5,(72 verified ratings)
38,2026-02-23,Dual SIM Dual Standby Foldable Mini Flip 2G Mo...,(134 verified ratings),23959,51703,4.1 out of 5,(134 verified ratings)
39,2026-02-23,Oppo A3S- 4G LTE Dual SIM 6.2'' 4GB RAM+64GB R...,(16 verified ratings),66090,149000,4.3 out of 5,(16 verified ratings)
40,2026-02-23,Philips Essence 20 6.56 HD Punch Hole 128GB RO...,Philips,112000,139000,4 out of 5,(31 verified ratings)
41,2026-02-23,Samsung Galaxy A06 4GB RAM + 64GB ROM BLACK,Samsung,120990,165000,3.9 out of 5,(63 verified ratings)
42,2026-02-23,Philips Fun100 Wireless FM - Deep Blue,Philips,9500,12300,4.1 out of 5,(352 verified ratings)
43,2026-02-23,Samsung Galaxy Note20 SINGLE SIM (128GB 8GB RA...,Samsung,298000,433794,3.9 out of 5,(28 verified ratings)
44,2026-02-23,"Poco C85 6.9"" 6GB RAM / 128GB ROM Xiaomi Hyper...",Poco,150295,157810,4.4 out of 5,(63 verified ratings)
45,2026-02-23,Philips Fun100 Wireless FM - Black,Philips,9500,12300,4.1 out of 5,(278 verified ratings)
46,2026-02-23,Samsung Galaxy A06 4GB RAM + 128GB ROM LIGHT BLUE,Samsung,142990,180000,4 out of 5,(73 verified ratings)
47,2026-02-23,itel it5095P Music 500 dual sim 2.8inc QQVA Su...,itel,22200,28990,4.5 out of 5,(20 verified ratings)
48,2026-02-23,"Samsung Galaxy A07 6.7"" 4GB RAM/64GBGB ROM - B...",Samsung,136693,147707,4.5 out of 5,(29 verified ratings)
49,2026-02-23,Oppo A3S 4GB RAM+ 64GB ROM-4G LTE Dual SIM -6....,(49 verified ratings),67050,93125,3.4 out of 5,(49 verified ratings)

In [11]:
df[df['Price'].str.contains('₦')]

,Today,Title,Brand,Price,Old Price,Rating,Reviews
37,2026-02-23,"Oukitel C61, 6.88"" HD+, 5150mAh, 16GB RAM + 12...",Oukitel,159920 - ₦ 160920,207229,3.3 out of 5,(72 verified ratings)
119,2026-02-23,"Oukitel C61, 6.88"" HD+, 5150mAh, 16GB RAM + 12...",Oukitel,159920 - ₦ 160920,207229,3.3 out of 5,(72 verified ratings)
281,2026-02-23,Multifunctional Rearview Mirror 360° Car Phone...,(98 verified ratings),3500 - ₦ 12500,4500 - ₦ 16000,4.2 out of 5,(98 verified ratings)
295,2026-02-23,XIAOMI Redmi Note 14 PRO+ 5G (12GB - 16GB RAM ...,XIAOMI,540000 - ₦ 580000,600000,5 out of 5,(2 verified ratings)

In [12]:
# extracting a single price in rows that have two prices

def extract_after_naira(value):
    value = str(value)
    if '₦' in value:
        match = re.search(r'₦\s*([\d,]+)', value)
        return match.group(1).replace(',', '') if match else np.nan
    else:
        return value

df['Price'] = df['Price'].apply(extract_after_naira)
df['Old Price'] = df['Old Price'].apply(extract_after_naira)

df.head(41)

,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,128468,131172,4 out of 5,(2010 verified ratings)
1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,109706,111330,4 out of 5,(919 verified ratings)
2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,179823,188814,4.2 out of 5,(1036 verified ratings)
3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.7 out of 5,(3175 verified ratings)
4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,142879,150023,4.1 out of 5,(396 verified ratings)
5,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,90100,105000,4 out of 5,(146 verified ratings)
6,2026-02-23,"itel 2165 Wireless FM, Torch, Dual SIM Phone +...",itel,9990,18000,3.7 out of 5,(2886 verified ratings)
7,2026-02-23,XIAOMI Redmi 15C 6.9'' 6GBRAM/128GB ROM Androi...,XIAOMI,153206,160866,4.4 out of 5,(147 verified ratings)
8,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,108200,118280,4.3 out of 5,(103 verified ratings)
9,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/64GB ROM Andro...",Samsung,118607,127518,4.1 out of 5,(1076 verified ratings)
10,2026-02-23,"Sunelan S7 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.7 out of 5,(2994 verified ratings)
11,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,90100,105000,4 out of 5,(73 verified ratings)
12,2026-02-23,"Philips Fun100 Wireless FM,2.0'' Big Screen,4M...",Philips,9400,12300,4 out of 5,(713 verified ratings)
13,2026-02-23,"C Idea C10 6.79 inch phone, 3GB Ram 64GB Rom s...",C Idea,81950,111750,3.3 out of 5,(126 verified ratings)
14,2026-02-23,"itel City 100 7.65mm"" Slim Design 5200mah And...",itel,123000,135910,4.1 out of 5,(364 verified ratings)
15,2026-02-23,"C Idea C11 6.79 inch phone,3GB Ram 64GB Rom st...",C Idea,81000,89400,3.2 out of 5,(166 verified ratings)
16,2026-02-23,"itel City 100 7.65mm"" Slim Design 5200mah And...",itel,123000,135910,4.1 out of 5,(215 verified ratings)
17,2026-02-23,"Sunelan S7 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.8 out of 5,(913 verified ratings)
18,2026-02-23,redbeat D5 Smartphone 6.52inch IPS HD 4GB + 64...,redbeat,84930,132610,3.8 out of 5,(188 verified ratings)
19,2026-02-23,"XIAOMI Redmi A3 Pro 6.88"" 4GB RAM / 128GB ROM ...",XIAOMI,124926,131172,3.9 out of 5,(413 verified ratings)
20,2026-02-23,"Poco C71 6.88"" 4GB RAM / 128GB ROM Android 15...",Poco,119721,125707,4.1 out of 5,(178 verified ratings)
21,2026-02-23,"XIAOMI Redmi A3 Pro 6.88"" 4GB RAM / 128GB ROM ...",XIAOMI,124926,131172,4 out of 5,(361 verified ratings)
22,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.8 out of 5,(972 verified ratings)
23,2026-02-23,"Poco C71 6.88"" 3GB RAM / 64GB ROM Android 15 ...",Poco,102182,107291,4.1 out of 5,(157 verified ratings)
24,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,108200,118280,4.3 out of 5,(73 verified ratings)
25,2026-02-23,"Poco C71 6.88"" 3GB RAM / 64GB ROM Android 15 -...",Poco,99999,107291,4.1 out of 5,(43 verified ratings)
26,2026-02-23,"FreeYond FreeYond M5,4GB+128GB,4G 6.52"" Smartp...",FreeYond,90499,195205,3.8 out of 5,(288 verified ratings)
27,2026-02-23,"Nokia 105_African Edition 1.77"" 4MB/4MB 800 MA...",Nokia,13150,24000,3.9 out of 5,(818 verified ratings)
28,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/ 128GB ROM And...",Samsung,140327,152100,4.2 out of 5,(563 verified ratings)
29,2026-02-23,CALLONG CA 800 Wireless FM Torchlight Dual SIM...,CALLONG,8200,17438,3.8 out of 5,(173 verified ratings)
30,2026-02-23,Samsung Galaxy A06 4GB RAM + 128GB ROM BLACK,Samsung,142990,180000,4.1 out of 5,(119 verified ratings)
31,2026-02-23,"AGM Note N1 6.52"" 8GB Base RAM/8GB Extended RA...",AGM,95860,153063,3.9 out of 5,(512 verified ratings)
32,2026-02-23,"Tecno T101 1.8"" Dual SIM - Black",Tecno,13263,13926,3.8 out of 5,(1362 verified ratings)
33,2026-02-23,"FreeYond FreeYond M5,8GB+128GB,4G 6.52"" Smartp...",FreeYond,93299,196188,4 out of 5,(256 verified ratings)
34,2026-02-23,XIAOMI Redmi 15 6.9'' 6GBRAM/128GB ROM Android...,XIAOMI,194368,204086,4.6 out of 5,(73 verified ratings)
35,2026-02-23,Philips Essence 20 6.56 HD Punch Hole 128GB RO...,Philips,112000,139020,4.1 out of 5,(76 verified ratings)
36,2026-02-23,"Samsung Galaxy A07 6.7"" 4GB RAM/ 128GB ROM And...",Samsung,160990,180000,4.2 out of 5,(108 verified ratings)
37,2026-02-23,"Oukitel C61, 6.88"" HD+, 5150mAh, 16GB RAM + 12...",Oukitel,160920,207229,3.3 out of 5,(72 verified ratings)
38,2026-02-23,Dual SIM Dual Standby Foldable Mini Flip 2G Mo...,(134 verified ratings),23959,51703,4.1 out of 5,(134 verified ratings)
39,2026-02-23,Oppo A3S- 4G LTE Dual SIM 6.2'' 4GB RAM+64GB R...,(16 verified ratings),66090,149000,4.3 out of 5,(16 verified ratings)
40,2026-02-23,Philips Essence 20 6.56 HD Punch Hole 128GB RO...,Philips,112000,139000,4 out of 5,(31 verified ratings)

In [14]:
df[['Price', 'Old Price']].isnull().sum()

Price        0
Old Price    0
dtype: int64

In [16]:
#Converting null values to NaN, to make it a recongnised null by pandas

df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Old Price'] = pd.to_numeric(df['Old Price'], errors='coerce')

In [17]:
df[['Price', 'Old Price']].isnull().sum()

Price         0
Old Price    74
dtype: int64

In [18]:
#Filling null old prices with current price, meaning there are not discounts on those products

df['Old Price'] = df['Old Price'].fillna(df['Price'])

In [19]:
#Converting prices to integer from strings

df['Old Price'] = df['Old Price'].astype(int)
df['Price'] = df['Price'].astype(int)

In [20]:
#Checking if error is fixed

df.info()
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Today      360 non-null    object
 1   Title      360 non-null    object
 2   Brand      360 non-null    object
 3   Price      360 non-null    int32
 4   Old Price  360 non-null    int32
 5   Rating     360 non-null    object
 6   Reviews    316 non-null    object
dtypes: int32(2), object(5)
memory usage: 17.0+ KB

Today        object
Title        object
Brand        object
Price         int32
Old Price     int32
Rating       object
Reviews      object
dtype: object

In [21]:
#Replacing Brand rows with null where value is having reviews instead of brand names

df['Brand'] = df['Brand'].apply(lambda x: np.nan if 'verified' in str(x).lower() else x)

df.head(41)

,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,128468,131172,4 out of 5,(2010 verified ratings)
1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,109706,111330,4 out of 5,(919 verified ratings)
2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,179823,188814,4.2 out of 5,(1036 verified ratings)
3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.7 out of 5,(3175 verified ratings)
4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,142879,150023,4.1 out of 5,(396 verified ratings)
5,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,90100,105000,4 out of 5,(146 verified ratings)
6,2026-02-23,"itel 2165 Wireless FM, Torch, Dual SIM Phone +...",itel,9990,18000,3.7 out of 5,(2886 verified ratings)
7,2026-02-23,XIAOMI Redmi 15C 6.9'' 6GBRAM/128GB ROM Androi...,XIAOMI,153206,160866,4.4 out of 5,(147 verified ratings)
8,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,108200,118280,4.3 out of 5,(103 verified ratings)
9,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/64GB ROM Andro...",Samsung,118607,127518,4.1 out of 5,(1076 verified ratings)
10,2026-02-23,"Sunelan S7 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.7 out of 5,(2994 verified ratings)
11,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,90100,105000,4 out of 5,(73 verified ratings)
12,2026-02-23,"Philips Fun100 Wireless FM,2.0'' Big Screen,4M...",Philips,9400,12300,4 out of 5,(713 verified ratings)
13,2026-02-23,"C Idea C10 6.79 inch phone, 3GB Ram 64GB Rom s...",C Idea,81950,111750,3.3 out of 5,(126 verified ratings)
14,2026-02-23,"itel City 100 7.65mm"" Slim Design 5200mah And...",itel,123000,135910,4.1 out of 5,(364 verified ratings)
15,2026-02-23,"C Idea C11 6.79 inch phone,3GB Ram 64GB Rom st...",C Idea,81000,89400,3.2 out of 5,(166 verified ratings)
16,2026-02-23,"itel City 100 7.65mm"" Slim Design 5200mah And...",itel,123000,135910,4.1 out of 5,(215 verified ratings)
17,2026-02-23,"Sunelan S7 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.8 out of 5,(913 verified ratings)
18,2026-02-23,redbeat D5 Smartphone 6.52inch IPS HD 4GB + 64...,redbeat,84930,132610,3.8 out of 5,(188 verified ratings)
19,2026-02-23,"XIAOMI Redmi A3 Pro 6.88"" 4GB RAM / 128GB ROM ...",XIAOMI,124926,131172,3.9 out of 5,(413 verified ratings)
20,2026-02-23,"Poco C71 6.88"" 4GB RAM / 128GB ROM Android 15...",Poco,119721,125707,4.1 out of 5,(178 verified ratings)
21,2026-02-23,"XIAOMI Redmi A3 Pro 6.88"" 4GB RAM / 128GB ROM ...",XIAOMI,124926,131172,4 out of 5,(361 verified ratings)
22,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.8 out of 5,(972 verified ratings)
23,2026-02-23,"Poco C71 6.88"" 3GB RAM / 64GB ROM Android 15 ...",Poco,102182,107291,4.1 out of 5,(157 verified ratings)
24,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,108200,118280,4.3 out of 5,(73 verified ratings)
25,2026-02-23,"Poco C71 6.88"" 3GB RAM / 64GB ROM Android 15 -...",Poco,99999,107291,4.1 out of 5,(43 verified ratings)
26,2026-02-23,"FreeYond FreeYond M5,4GB+128GB,4G 6.52"" Smartp...",FreeYond,90499,195205,3.8 out of 5,(288 verified ratings)
27,2026-02-23,"Nokia 105_African Edition 1.77"" 4MB/4MB 800 MA...",Nokia,13150,24000,3.9 out of 5,(818 verified ratings)
28,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/ 128GB ROM And...",Samsung,140327,152100,4.2 out of 5,(563 verified ratings)
29,2026-02-23,CALLONG CA 800 Wireless FM Torchlight Dual SIM...,CALLONG,8200,17438,3.8 out of 5,(173 verified ratings)
30,2026-02-23,Samsung Galaxy A06 4GB RAM + 128GB ROM BLACK,Samsung,142990,180000,4.1 out of 5,(119 verified ratings)
31,2026-02-23,"AGM Note N1 6.52"" 8GB Base RAM/8GB Extended RA...",AGM,95860,153063,3.9 out of 5,(512 verified ratings)
32,2026-02-23,"Tecno T101 1.8"" Dual SIM - Black",Tecno,13263,13926,3.8 out of 5,(1362 verified ratings)
33,2026-02-23,"FreeYond FreeYond M5,8GB+128GB,4G 6.52"" Smartp...",FreeYond,93299,196188,4 out of 5,(256 verified ratings)
34,2026-02-23,XIAOMI Redmi 15 6.9'' 6GBRAM/128GB ROM Android...,XIAOMI,194368,204086,4.6 out of 5,(73 verified ratings)
35,2026-02-23,Philips Essence 20 6.56 HD Punch Hole 128GB RO...,Philips,112000,139020,4.1 out of 5,(76 verified ratings)
36,2026-02-23,"Samsung Galaxy A07 6.7"" 4GB RAM/ 128GB ROM And...",Samsung,160990,180000,4.2 out of 5,(108 verified ratings)
37,2026-02-23,"Oukitel C61, 6.88"" HD+, 5150mAh, 16GB RAM + 12...",Oukitel,160920,207229,3.3 out of 5,(72 verified ratings)
38,2026-02-23,Dual SIM Dual Standby Foldable Mini Flip 2G Mo...,NaN,23959,51703,4.1 out of 5,(134 verified ratings)
39,2026-02-23,Oppo A3S- 4G LTE Dual SIM 6.2'' 4GB RAM+64GB R...,NaN,66090,149000,4.3 out of 5,(16 verified ratings)
40,2026-02-23,Philips Essence 20 6.56 HD Punch Hole 128GB RO...,Philips,112000,139000,4 out of 5,(31 verified ratings)

In [22]:
#checking for null brand rows

df[df['Brand'].isna()][['Title', 'Brand']]

                                                 Title Brand
38   Dual SIM Dual Standby Foldable Mini Flip 2G Mo...   NaN
39   Oppo A3S- 4G LTE Dual SIM 6.2'' 4GB RAM+64GB R...   NaN
49   Oppo A3S 4GB RAM+ 64GB ROM-4G LTE Dual SIM -6....   NaN
65   Huawei Honor 8X 6.5-inch 6GB RAM 128GB ROM Kir...   NaN
67   Huawei Honor 8X 6.5"6GB+128GB 3750mAh 16MP+2MP...   NaN
87   Huawei Honor 8X 6.5"6GB RAM+128GB ROM 3750mAh ...   NaN
89   Vivo Y19 smartphone 8+128GB ROM Dual SIM 6.53-...   NaN
109  Dual SIM Dual Standby Foldable Mini Flip 2G Mo...   NaN
123  Magnetic Foldable Portable Phone Holder Mobile...   NaN
128  Car mobile phone holder does not block the air...   NaN
159  Renewed Huawei Y5P Black 5.45" 4+64G 8MP 3020m...   NaN
173  Vivo Y93s Black 6.2" 6+128G 13MP+2MP 4030mAh W...   NaN
174  OPPO A3s Purple 6.2" 4+64G 13MP+2MP 3400mAh Wi...   NaN
182       Car Cell Phone Holder 360 Rotating Car Mount   NaN
193       Rotational Desktop Phone Stand Holder- Black   NaN
205  Iphone 6 - 4.7" 1GB RAM+64GB ROM 99.9%NEW- 8Mp...   NaN
214  4 SHOCK PAD FOR WASHING MACHINE REFRIGERATOR F...   NaN
218  OPPO A31 Black 6.5" 6+128G 12MP+2MP+2MP 4230mA...   NaN
220  360° Universal Adjustable Dashboard Car Phone ...   NaN
236  4 SHOCK PAD FOR WASHING MACHINE REFRIGERATOR F...   NaN
237  Huawei Y5P 2020  Green 4GB 64GB  5.45" HD+ Dis...   NaN
241  12inch 3D Mobile Phone Screen Magnifier HD Vid...   NaN
244  OPPO  A5s Green 6GB 128GB 6.2'' HD+ 13MP DUAL ...   NaN
251  12inch 3D Mobile Phone Screen Magnifier HD Vid...   NaN
255  Adjustable Car Rearview Mirror Mount Phone Hol...   NaN
281  Multifunctional Rearview Mirror 360° Car Phone...   NaN
307  XIAOMI Redmi 5 Plus 5.99"4GB+64GB Battery 4000...   NaN
331  Adjustable Refrigerator And Washing Machine Mo...   NaN
332  Adjustable Washing Machine/ Fridge Base Stand ...   NaN
352  Adjustable Washing Machine/ Fridge Base Stand ...   NaN

In [23]:
# Fixing null brand names by identifying brand name from title and removing items that don't have brand names
brand_map = {
    'oppo': 'Oppo',
    'huawei': 'Huawei',
    'vivo': 'Vivo',
    'iphone': 'Apple',
    'xiaomi': 'XIAMi',
}

def fill_brand(row):
    if pd.isna(row['Brand']):
        for keyword, brand in brand_map.items():
            if keyword.lower() in row['Title'].lower():
                return brand
    return row['Brand']

df['Brand'] = df.apply(fill_brand, axis=1)

# dropping any item that has missing brand names even in the title
df.dropna(subset=['Brand'], inplace=True)

df[df['Brand'].isna()][['Title', 'Brand']]

Empty DataFrame
Columns: [Title, Brand]
Index: []

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 345 entries, 0 to 359
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Today      345 non-null    object
 1   Title      345 non-null    object
 2   Brand      345 non-null    object
 3   Price      345 non-null    int32
 4   Old Price  345 non-null    int32
 5   Rating     345 non-null    object
 6   Reviews    301 non-null    object
dtypes: int32(2), object(5)
memory usage: 18.9+ KB

In [25]:
# Clean Rating: Extracting just the rating numbers from the rating column 
df['Rating'] = df['Rating'].astype(str).str.extract(r'([\d.]+)').astype(float)

df.head(10)

,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,128468,131172,4.0,(2010 verified ratings)
1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,109706,111330,4.0,(919 verified ratings)
2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,179823,188814,4.2,(1036 verified ratings)
3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.7,(3175 verified ratings)
4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,142879,150023,4.1,(396 verified ratings)
5,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,90100,105000,4.0,(146 verified ratings)
6,2026-02-23,"itel 2165 Wireless FM, Torch, Dual SIM Phone +...",itel,9990,18000,3.7,(2886 verified ratings)
7,2026-02-23,XIAOMI Redmi 15C 6.9'' 6GBRAM/128GB ROM Androi...,XIAOMI,153206,160866,4.4,(147 verified ratings)
8,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,108200,118280,4.3,(103 verified ratings)
9,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/64GB ROM Andro...",Samsung,118607,127518,4.1,(1076 verified ratings)

In [27]:
# Clean Reviews: Extracting just the numbers number of reviews from the review column 

df['Reviews'] = df['Reviews'].astype(str).str.extract(r'([\d,]+)')[0].str.replace(',', '').astype(float)

df.head(10)

,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,128468,131172,4.0,2010.0
1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,109706,111330,4.0,919.0
2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,179823,188814,4.2,1036.0
3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.7,3175.0
4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,142879,150023,4.1,396.0
5,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,90100,105000,4.0,146.0
6,2026-02-23,"itel 2165 Wireless FM, Torch, Dual SIM Phone +...",itel,9990,18000,3.7,2886.0
7,2026-02-23,XIAOMI Redmi 15C 6.9'' 6GBRAM/128GB ROM Androi...,XIAOMI,153206,160866,4.4,147.0
8,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,108200,118280,4.3,103.0
9,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/64GB ROM Andro...",Samsung,118607,127518,4.1,1076.0

In [28]:
df.dtypes

Today         object
Title         object
Brand         object
Price          int32
Old Price      int32
Rating       float64
Reviews      float64
dtype: object

In [29]:
#Converting reviews column to integer

df['Reviews'] = df['Reviews'].fillna(0).astype(int)

In [30]:
#Confirming if reviews have been converted to integer

df.dtypes

Today         object
Title         object
Brand         object
Price          int32
Old Price      int32
Rating       float64
Reviews        int32
dtype: object

In [31]:
df.head(10)

,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,128468,131172,4.0,2010
1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,109706,111330,4.0,919
2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,179823,188814,4.2,1036
3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.7,3175
4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,142879,150023,4.1,396
5,2026-02-23,"itel itel A100C 64/2+4gb 90hz 6.6"" Super Clear...",itel,90100,105000,4.0,146
6,2026-02-23,"itel 2165 Wireless FM, Torch, Dual SIM Phone +...",itel,9990,18000,3.7,2886
7,2026-02-23,XIAOMI Redmi 15C 6.9'' 6GBRAM/128GB ROM Androi...,XIAOMI,153206,160866,4.4,147
8,2026-02-23,itel A100 6.75'' 90hz Bright Display IP65 5000...,itel,108200,118280,4.3,103
9,2026-02-23,"Samsung Galaxy A06 6.7"" 4GB RAM/64GB ROM Andro...",Samsung,118607,127518,4.1,1076

In [32]:
#Checking for more null values

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 345 entries, 0 to 359
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Today      345 non-null    object
 1   Title      345 non-null    object
 2   Brand      345 non-null    object
 3   Price      345 non-null    int32
 4   Old Price  345 non-null    int32
 5   Rating     345 non-null    float64
 6   Reviews    345 non-null    int32
dtypes: float64(1), int32(3), object(3)
memory usage: 17.5+ KB

In [33]:
df[df['Reviews'].isna()][['Title', 'Reviews']]

Empty DataFrame
Columns: [Title, Reviews]
Index: []

In [34]:
#Filling empty review rows with 0 because they could be new product listings amongst them

df['Reviews'] = df['Reviews'].fillna(0).astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 345 entries, 0 to 359
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Today      345 non-null    object
 1   Title      345 non-null    object
 2   Brand      345 non-null    object
 3   Price      345 non-null    int32
 4   Old Price  345 non-null    int32
 5   Rating     345 non-null    float64
 6   Reviews    345 non-null    int32
dtypes: float64(1), int32(3), object(3)
memory usage: 17.5+ KB

In [35]:
df

,Today,Title,Brand,Price,Old Price,Rating,Reviews
0,2026-02-23,XIAOMI REDMI A5 - 6.88 4GB RAM/128GB ROM -...,XIAOMI,128468,131172,4.0,2010
1,2026-02-23,XIAOMI REDMI A5 - 6.88 3GB RAM/64GB ROM --...,XIAOMI,109706,111330,4.0,919
2,2026-02-23,XIAOMI Redmi 15C 6.9'' 8GBRAM/256GB ROM Androi...,XIAOMI,179823,188814,4.2,1036
3,2026-02-23,"Sunelan S8 1.8"" Screen Phone, Dual SIM, Game, ...",Sunelan,6846,7188,3.7,3175
4,2026-02-23,XIAOMI Redmi 15C 6.9'' 4GBRAM/128GB ROM Androi...,XIAOMI,142879,150023,4.1,396
...,...,...,...,...,...,...,...
355,2026-02-23,"Samsung Galaxy S20 5G - 6.2"" 128GB/12GB, Singl...",Samsung,260000,300000,4.1,7
356,2026-02-23,"Doogee Local Stock Note58 6.75"" iPhone-Style 5...",Doogee,184439,430610,0.0,0
357,2026-02-23,"Samsung Galaxy A17 5G 6.7"" 8GB RAM 256GB ROM ...",Samsung,335000,335000,4.0,1
358,2026-02-23,"Samsung Galaxy S22 Ultra 5G- 6.8"" - 256GB ROM,...",Samsung,610000,610000,5.0,2
359,2026-02-23,"Samsung Galaxy A56 5G 6.7"" 8GB RAM 256GB ROM ...",Samsung,540000,540000,4.8,9

In [39]:
# Exporting cleaned data

df.to_csv(r"C:\Users\ikeol\OneDrive\Documents\Web-Scraping\Data\Jumia cleaned data.csv", index = False)

print("File exported Successfully! 👍")

File exported Successfully! 👍